Fluent Pom project
steven7324/stevenProject pull request #11
Opened 2021-10-08 22:57 UTC by steven7324

2021-10-11 15:30 UTC, aperdomob requested changes
No veo la implementación del fluent para todos los page objects, y segun entiendo la implmentación que hiciste veo que quitaste muchas propiedades, entonces no entiendo como ahora es capaz de realizar la misma prueba que hacía antes

2021-10-11 15:30 UTC, aperdomob commented on src/test/java/com/automation/drivers/instantiateDriver.java
> +public class instantiateDriver {
las clases empiezan en mayuscula

2021-10-20 14:21 UTC, aperdomob requested changes

2021-10-20 14:21 UTC, aperdomob commented on build.gradle
> -    implementation 'org.projectlombok:lombok:1.18.20'
why do you remove it?

2021-10-20 14:30 UTC, steven7324 commented on build.gradle
> -    implementation 'org.projectlombok:lombok:1.18.20'
Because it was duplicated

2021-10-21 12:28 UTC, aperdomob approved these changes

2021-10-21 12:28 UTC, merged